#!/bin/bash

gateway=google.com

# Timeout: 1
# Count: 1
ping -c 1 -W 1 $gateway >/dev/null 2>&1

ping_status=$?

fg_color_error=`polybar --dump=alert-bright base`
bg_color=`polybar --dump=background base`

if [[ "$ping_status" == "0" ]]; then
    echo ""
else
    echo "%{B$fg_color_error F$bg_color}Could not ping $gateway%{F- B-}";
fi
