#!/bin/bash

# The first `cat` is necessary to get sudo privileges without the `fzf` UI interfering

sudo /usr/bin/usbguard list-devices --blocked | rofi -dmenu| sed -E 's/^([^:]*):.*/\1/' | xargs gksudo usbguard allow-device
